# Generated by Django 3.0.5 on 2021-11-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_auto_20210213_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonate',
            name='date',
            field=models.DateField(),
        ),
    ]
